#!/usr/bin/python

import RPi.GPIO as GPIO
import time
from smbus2 import SMBus, i2c_msg

EVENT_ID = 0
EVENT_ERROR = 1
EVENT_STATE = 2
EVENT_NODATA = 0xfe

DEV_ADDR = 0x06

bus = SMBus(1)


def reader_request_callback(gpio):
	while True:
		msg = i2c_msg.read(DEV_ADDR, 6)
		bus.i2c_rdwr(msg)
		data = list(msg)

		event = data[0]
		
		if event == EVENT_NODATA:
			break
		
		bits = data[1]
		bytes = (bits + 7) / 8
		print(str(bytes) + " bytes")
		for i in range(0, bytes):
			print(hex(data[i + 2]))

GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.add_event_detect(4, GPIO.FALLING, callback=reader_request_callback)

if GPIO.input(4) == GPIO.LOW:
	reader_request_callback(4)

while True:
	time.sleep(10)

GPIO.cleanup()
